namespace: sahil-ns 

replicas: 2

appDeployment:
 labels:
  app: ecommerce
 name: ecommerce-conatiner

image:
 repository: svsps/ecommerce-app
 tag: v1.0.1
port: 80

appService:
 app: ecommerce
 port: 80
 type: LoadBalancer


